In [ ]:
import pandas as pd
df_sales_records = pd.read_csv('/content/1000 Sales Records.csv')

df_sales_records

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Middle East and North Africa,Libya,Cosmetics,Offline,M,10/18/2014,686800706,10/31/2014,8446,437.20,263.33,3692591.20,2224085.18,1468506.02
1,North America,Canada,Vegetables,Online,M,11-07-2011,185941302,12-08-2011,3018,154.06,90.93,464953.08,274426.74,190526.34
2,Middle East and North Africa,Libya,Baby Food,Offline,C,10/31/2016,246222341,12-09-2016,1517,255.28,159.42,387259.76,241840.14,145419.62
3,Asia,Japan,Cereal,Offline,C,04-10-2010,161442649,05-12-2010,3322,205.70,117.11,683335.40,389039.42,294295.98
4,Sub-Saharan Africa,Chad,Fruits,Offline,H,8/16/2011,645713555,8/31/2011,9845,9.33,6.92,91853.85,68127.40,23726.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Middle East and North Africa,Azerbaijan,Snacks,Offline,C,4/18/2010,534085166,4/25/2010,6524,152.58,97.44,995431.92,635698.56,359733.36
996,Europe,Georgia,Baby Food,Offline,H,08-01-2011,590768182,09-07-2011,288,255.28,159.42,73520.64,45912.96,27607.68
997,Middle East and North Africa,United Arab Emirates,Vegetables,Online,C,05-12-2011,524363124,6/28/2011,9556,154.06,90.93,1472197.36,868927.08,603270.28
998,Europe,Finland,Household,Offline,L,1/25/2016,289606320,2/14/2016,9801,668.27,502.54,6549714.27,4925394.54,1624319.73
999,Europe,Portugal,Cereal,Offline,C,04-10-2014,811546599,05-08-2014,3528,205.70,117.11,725709.60,413164.08,312545.52

In [ ]:
print(df_sales_records.info())
print(df_sales_records.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          1000 non-null   object
 1   Country         1000 non-null   object
 2   Item Type       1000 non-null   object
 3   Sales Channel   1000 non-null   object
 4   Order Priority  1000 non-null   object
 5   Order Date      1000 non-null   object
 6   Order ID        1000 non-null   int64
 7   Ship Date       1000 non-null   object
 8   Units Sold      1000 non-null   int64
 9   Unit Price      1000 non-null   float64
 10  Unit Cost       1000 non-null   float64
 11  Total Revenue   1000 non-null   float64
 12  Total Cost      1000 non-null   float64
 13  Total Profit    1000 non-null   float64
dtypes: float64(5), int64(2), object(7)
memory usage: 109.5+ KB
None
           Order ID   Units Sold  Unit Price    Unit Cost  Total Revenue  \
count  1.000000e+03  1000.000000  1000.00000  1000.000000   1.000000e+03
mean   5.496813e+08  5053.988000   262.10684   184.965110   1.327322e+06
std    2.571334e+08  2901.375317   216.02106   175.289311   1.486515e+06
min    1.029280e+08    13.000000     9.33000     6.920000   2.043250e+03
25%    3.280740e+08  2420.250000    81.73000    56.670000   2.811919e+05
50%    5.566097e+08  5184.000000   154.06000    97.440000   7.549392e+05
75%    7.696945e+08  7536.750000   421.89000   263.330000   1.733503e+06
max    9.955298e+08  9998.000000   668.27000   524.960000   6.617210e+06

         Total Cost  Total Profit
count  1.000000e+03  1.000000e+03
mean   9.361192e+05  3.912026e+05
std    1.162571e+06  3.836402e+05
min    1.416750e+03  5.326100e+02
25%    1.649319e+05  9.837612e+04
50%    4.647261e+05  2.772260e+05
75%    1.141750e+06  5.484568e+05
max    5.204978e+06  1.726181e+06

In [ ]:
print(df_sales_records.isnull().sum())

Region            0
Country           0
Item Type         0
Sales Channel     0
Order Priority    0
Order Date        0
Order ID          0
Ship Date         0
Units Sold        0
Unit Price        0
Unit Cost         0
Total Revenue     0
Total Cost        0
Total Profit      0
dtype: int64

In [ ]:
#Sales by Region
sales_by_region = df_sales_records.groupby('Region')['Total Revenue'].sum()

print(sales_by_region)

Region
Asia                                 1.676748e+08
Australia and Oceania                1.056896e+08
Central America and the Caribbean    1.439976e+08
Europe                               3.531675e+08
Middle East and North Africa         1.751065e+08
North America                        2.496160e+07
Sub-Saharan Africa                   3.567243e+08
Name: Total Revenue, dtype: float64

In [ ]:
#Total Revenue by Country
total_revenue_by_country = df_sales_records.groupby('Country')['Total Revenue'].sum()

print(total_revenue_by_country)

Country
Afghanistan      2843589.07
Albania          9709899.27
Algeria         10272591.44
Andorra          7153122.97
Angola          15643032.02
                   ...
Vatican City     1575379.28
Vietnam         11668032.25
Yemen           11813464.95
Zambia           1954116.20
Zimbabwe         6928978.02
Name: Total Revenue, Length: 185, dtype: float64

In [ ]:
#Average Profit by Item Type
average_profit_by_item_type = df_sales_records.groupby('Item Type')['Total Profit'].mean()

print(average_profit_by_item_type)

Item Type
Baby Food          481082.775632
Beverages           78285.270297
Cereal             434818.783671
Clothes            355888.356923
Cosmetics          987748.515200
Fruits              12226.446429
Household          798500.054026
Meat               299137.666667
Office Supplies    630515.196629
Personal Care      137030.384368
Snacks             265710.245854
Vegetables         306718.081237
Name: Total Profit, dtype: float64

In [ ]:
#Correlation Analysis
correlation_matrix = df_sales_records.select_dtypes(include=['number']).corr()

print(correlation_matrix)

               Order ID  Units Sold  Unit Price  Unit Cost  Total Revenue  \
Order ID       1.000000    0.010266   -0.033436  -0.035550      -0.022079
Units Sold     0.010266    1.000000    0.004212   0.002574       0.527945
Unit Price    -0.033436    0.004212    1.000000   0.986735       0.730752
Unit Cost     -0.035550    0.002574    0.986735   1.000000       0.717999
Total Revenue -0.022079    0.527945    0.730752   0.717999       1.000000
Total Cost    -0.025629    0.479713    0.745538   0.753678       0.987779
Total Profit  -0.007886    0.591957    0.572235   0.498156       0.881429

               Total Cost  Total Profit
Order ID        -0.025629     -0.007886
Units Sold       0.479713      0.591957
Unit Price       0.745538      0.572235
Unit Cost        0.753678      0.498156
Total Revenue    0.987779      0.881429
Total Cost       1.000000      0.797041
Total Profit     0.797041      1.000000

In [ ]:
#Top 10 Orders by Total Revenue
top_10_orders = df_sales_records.nlargest(10, 'Total Revenue')

print(top_10_orders)

                                Region                   Country  \
286                             Europe            Czech Republic
952              Australia and Oceania          Papua New Guinea
554                               Asia                  Mongolia
998                             Europe                   Finland
36                  Sub-Saharan Africa                 Swaziland
943                               Asia                    Bhutan
582  Central America and the Caribbean                      Cuba
238  Central America and the Caribbean                Costa Rica
976                 Sub-Saharan Africa  Central African Republic
311                      North America                 Greenland

           Item Type Sales Channel Order Priority  Order Date   Order ID  \
286        Household        Online              L   2/27/2010  494525372
952        Household        Online              M   3/14/2012  442214143
554        Household        Online              C  02-05-2013  428392827
998        Household       Offline              L   1/25/2016  289606320
36   Office Supplies       Offline              H  10-03-2013  405785882
943  Office Supplies       Offline              M  10/19/2011  221007430
582        Household       Offline              H   7/28/2013  714818418
238  Office Supplies        Online              H   6/20/2010  953293836
976        Household        Online              H  01-10-2010  256994950
311        Household        Online              L   4/17/2014  192721068

      Ship Date  Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  \
286  03-02-2010        9902      668.27     502.54     6617209.54  4976151.08
952  05-03-2012        9847      668.27     502.54     6580454.69  4948511.38
554  02-05-2013        9812      668.27     502.54     6557065.24  4930922.48
998   2/14/2016        9801      668.27     502.54     6549714.27  4925394.54
36   10/22/2013        9915      651.21     524.96     6456747.15  5204978.40
943  11-10-2011        9865      651.21     524.96     6424186.65  5178730.40
582   8/24/2013        9509      668.27     502.54     6354579.43  4778652.86
238   7/22/2010        9685      651.21     524.96     6306968.85  5084237.60
976   2/19/2010        9372      668.27     502.54     6263026.44  4709804.88
311   5/20/2014        9302      668.27     502.54     6216247.54  4674627.08

     Total Profit
286    1641058.46
952    1631943.31
554    1626142.76
998    1624319.73
36     1251768.75
943    1245456.25
582    1575926.57
238    1222731.25
976    1553221.56
311    1541620.46

In [ ]:
top_orders = df_sales_records.sort_values(by='Total Revenue', ascending=False).head(10)

print(top_orders)

                                Region                   Country  \
286                             Europe            Czech Republic
952              Australia and Oceania          Papua New Guinea
554                               Asia                  Mongolia
998                             Europe                   Finland
36                  Sub-Saharan Africa                 Swaziland
943                               Asia                    Bhutan
582  Central America and the Caribbean                      Cuba
238  Central America and the Caribbean                Costa Rica
976                 Sub-Saharan Africa  Central African Republic
311                      North America                 Greenland

           Item Type Sales Channel Order Priority  Order Date   Order ID  \
286        Household        Online              L   2/27/2010  494525372
952        Household        Online              M   3/14/2012  442214143
554        Household        Online              C  02-05-2013  428392827
998        Household       Offline              L   1/25/2016  289606320
36   Office Supplies       Offline              H  10-03-2013  405785882
943  Office Supplies       Offline              M  10/19/2011  221007430
582        Household       Offline              H   7/28/2013  714818418
238  Office Supplies        Online              H   6/20/2010  953293836
976        Household        Online              H  01-10-2010  256994950
311        Household        Online              L   4/17/2014  192721068

      Ship Date  Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  \
286  03-02-2010        9902      668.27     502.54     6617209.54  4976151.08
952  05-03-2012        9847      668.27     502.54     6580454.69  4948511.38
554  02-05-2013        9812      668.27     502.54     6557065.24  4930922.48
998   2/14/2016        9801      668.27     502.54     6549714.27  4925394.54
36   10/22/2013        9915      651.21     524.96     6456747.15  5204978.40
943  11-10-2011        9865      651.21     524.96     6424186.65  5178730.40
582   8/24/2013        9509      668.27     502.54     6354579.43  4778652.86
238   7/22/2010        9685      651.21     524.96     6306968.85  5084237.60
976   2/19/2010        9372      668.27     502.54     6263026.44  4709804.88
311   5/20/2014        9302      668.27     502.54     6216247.54  4674627.08

     Total Profit
286    1641058.46
952    1631943.31
554    1626142.76
998    1624319.73
36     1251768.75
943    1245456.25
582    1575926.57
238    1222731.25
976    1553221.56
311    1541620.46

In [ ]:
#Orders with High Priority
high_priority_orders = df_sales_records[df_sales_records['Order Priority'] == 'H']

print(high_priority_orders)

                                Region      Country      Item Type  \
4                   Sub-Saharan Africa         Chad         Fruits
5                               Europe      Armenia         Cereal
6                   Sub-Saharan Africa      Eritrea         Cereal
8    Central America and the Caribbean      Jamaica     Vegetables
9                Australia and Oceania         Fiji     Vegetables
..                                 ...          ...            ...
982                             Europe  Switzerland         Snacks
984                 Sub-Saharan Africa      Comoros  Personal Care
986                               Asia     Mongolia        Clothes
991                 Sub-Saharan Africa      Liberia         Cereal
996                             Europe      Georgia      Baby Food

    Sales Channel Order Priority  Order Date   Order ID   Ship Date  \
4         Offline              H   8/16/2011  645713555   8/31/2011
5          Online              H  11/24/2014  683458888  12/28/2014
6          Online              H  03-04-2015  679414975   4/17/2015
8          Online              H   1/29/2015  266467225  03-07-2015
9         Offline              H  12/24/2013  118598544   1/19/2014
..            ...            ...         ...        ...         ...
982        Online              H   5/27/2016  359911954   6/23/2016
984       Offline              H  12/31/2014  864981782  02-11-2015
986       Offline              H   9/23/2016  308168065  10/18/2016
991       Offline              H  12/17/2015  642683303   1/20/2016
996       Offline              H  08-01-2011  590768182  09-07-2011

     Units Sold  Unit Price  Unit Cost  Total Revenue  Total Cost  \
4          9845        9.33       6.92       91853.85    68127.40
5          9528      205.70     117.11     1959909.60  1115824.08
6          2844      205.70     117.11      585010.80   333060.84
8          2428      154.06      90.93      374057.68   220778.04
9          4800      154.06      90.93      739488.00   436464.00
..          ...         ...        ...            ...         ...
982        4800      152.58      97.44      732384.00   467712.00
984        6186       81.73      56.67      505581.78   350560.62
986        2633      109.28      35.84      287734.24    94366.72
991        3126      205.70     117.11      643018.20   366085.86
996         288      255.28     159.42       73520.64    45912.96

     Total Profit
4        23726.45
5       844085.52
6       251949.96
8       153279.64
9       303024.00
..            ...
982     264672.00
984     155021.16
986     193367.52
991     276932.34
996      27607.68

[228 rows x 14 columns]

In [ ]:
#Average Sales
average_sales = df_sales_records['Total Revenue'].mean()

print(average_sales)

1327321.84033

In [ ]:
#number of orders per country
orders_per_country = df_sales_records.groupby('Country')['Order ID'].count()

print(orders_per_country)

Country
Afghanistan      6
Albania          8
Algeria          5
Andorra          7
Angola           8
                ..
Vatican City     4
Vietnam          7
Yemen            6
Zambia           2
Zimbabwe        10
Name: Order ID, Length: 185, dtype: int64

In [ ]:
orders_by_country = df_sales_records['Country'].value_counts()
print(orders_by_country)

Country
Cuba              11
Czech Republic    10
Bahrain           10
Zimbabwe          10
Malaysia          10
                  ..
Denmark            2
The Gambia         2
Kosovo             1
Malta              1
Cameroon           1
Name: count, Length: 185, dtype: int64

In [ ]:
#Filter data for a specific region
region_data_filter = df_sales_records[df_sales_records['Region'] == 'North America']

print(region_data_filter)

            Region                   Country        Item Type Sales Channel  \
1    North America                    Canada       Vegetables        Online
17   North America                 Greenland        Beverages        Online
27   North America                 Greenland           Fruits       Offline
79   North America  United States of America  Office Supplies        Online
100  North America  United States of America          Clothes       Offline
177  North America                    Mexico          Clothes        Online
191  North America  United States of America        Baby Food       Offline
193  North America                    Canada       Vegetables       Offline
311  North America                 Greenland        Household        Online
318  North America                 Greenland        Baby Food       Offline
332  North America  United States of America        Beverages        Online
365  North America                 Greenland        Baby Food       Offline
441  North America                    Canada        Beverages        Online
466  North America                 Greenland          Clothes        Online
479  North America  United States of America    Personal Care       Offline
486  North America  United States of America             Meat        Online
703  North America                 Greenland          Clothes        Online
753  North America                 Greenland           Snacks       Offline
927  North America                    Mexico        Baby Food        Online

    Order Priority  Order Date   Order ID   Ship Date  Units Sold  Unit Price  \
1                M  11-07-2011  185941302  12-08-2011        3018      154.06
17               M   7/27/2012  414244067  08-07-2012        2880       47.45
27               M   1/31/2012  469839179   2/22/2012        4709        9.33
79               C  06-09-2017  811701095   7/19/2017        9247      651.21
100              C  10/21/2010  699368035  12-07-2010        7398      109.28
177              H  11/18/2012  654693591  12-01-2012        7237      109.28
191              C   2/13/2015  984673964  03-05-2015        5763      255.28
193              L  10-07-2016  654480731  11-08-2016        4247      154.06
311              L   4/17/2014  192721068   5/20/2014        9302      668.27
318              C  07-08-2014  360945355   8/16/2014         607      255.28
332              L   7/13/2013  799003732   7/14/2013        1815       47.45
365              H   3/19/2011  313044536   4/14/2011        5689      255.28
441              C   4/16/2016  694687259  06-02-2016        2252       47.45
466              H  10/20/2015  509214437  11-02-2015        6722      109.28
479              C   7/16/2010  551057326   8/22/2010        8963       81.73
486              M  03-06-2011  908136594  03-10-2011        6654      421.89
703              L   1/28/2011  851299941  02-01-2011        7425      109.28
753              L   6/24/2010  977499377  08-12-2010        2643      152.58
927              H   8/17/2013  434355056   9/28/2013        4168      255.28

     Unit Cost  Total Revenue  Total Cost  Total Profit
1        90.93      464953.08   274426.74     190526.34
17       31.79      136656.00    91555.20      45100.80
27        6.92       43934.97    32586.28      11348.69
79      524.96     6021738.87  4854305.12    1167433.75
100      35.84      808453.44   265144.32     543309.12
177      35.84      790859.36   259374.08     531485.28
191     159.42     1471178.64   918737.46     552441.18
193      90.93      654292.82   386179.71     268113.11
311     502.54     6216247.54  4674627.08    1541620.46
318     159.42      154954.96    96767.94      58187.02
332      31.79       86121.75    57698.85      28422.90
365     159.42     1452287.92   906940.38     545347.54
441      31.79      106857.40    71591.08      35266.32
466      35.84      734580.16   240916.48     493663.68
479      56.67      732545.99   507933.21     224612.78
486     364.69     2807256.06  2426647.26     380608.80
703      35.84      811404.00   266112.00     545292.00
753      97.44      403268.94   257533.92     145735.02
927     159.42     1064007.04   664462.56     399544.48

In [ ]:
#least common item type
least_common_item_type = df_sales_records['Item Type'].value_counts().idxmin()

print(least_common_item_type)

Fruits

In [ ]:
item_counts = df_sales_records['Item Type'].value_counts()
least_common_item = item_counts.idxmin()

print(f"The least common item type is: {least_common_item}")

The least common item type is: Fruits

In [ ]:
#Most common item type
most_common_item_type = df_sales_records['Item Type'].value_counts().idxmax()

print(most_common_item_type)

Beverages

In [ ]:
most_common_item = item_counts.idxmax()

print(f"The most common item type is: {most_common_item}")

The most common item type is: Beverages